### ISSUE TITLE
Transformer Question, and Request

### ISSUE THREAD

**Issue by johngrabner** [AladdinPerzon/Machine-Learning-Collection#3]
Learning PyTorch and love your videos. Your code is so clean and your explanations so crisp.

**Question/Bug?:**
In SelfAttention you split values, keys, and query by the number of heads.  Then pass this into Linear with same input  and output dimension. Why not keep the full dimension (ie: not split) and let the Linear do the reduction?
This would allow linear to learn what to take out of the input rather?

btw, https://github.com/tunz/transformer-pytorch/blob/master/model/transformer.py, class MultiHeadAttention(nn.Module) does this (if I interpret their code correctly).

The paper https://arxiv.org/pdf/1706.03762.pdf indicates "learned
linear projections to dk, dk and dv dimensions".

If I'm all wrong, would love to be corrected as I learning.
If I'm right, would also love to know that I'm starting to understand this stuff.

**Request:**
Starting to understand torch.einsum power but I am sure I am missing a bunch.
Can you do a video on this?  

Regards,
John

**Comment by AladdinPerzon** [comment]
You bring up a great point! There was another question regarding this on the video I made, where my answer was:

> Hey, thank you so much for bringing this to my attention ;) When reading through the paper I get the same idea that you do, namely that each head should have separate weights, and when reading blog posts like "The Annotated Transformer" he has done exactly what you describe. From the blog post http://www.peterbloem.nl/blog/transformers he explains narrow vs wide self attention and in his Github implementation he does similarly as I do, however I noticed now that an issue has been raised regarding the same issue you bring up: https://github.com/pbloem/former/issues/13. I agree with the point brought up there also, if each head is using same weights it doesn't feel like you can say they are different. I'm having difficulty finding other implementations, but I will keep a close look at this and if I get some more time I will try to spend more time and investigate this. I'm also a bit surprised that when training on this implementation it provides good results if I remember correctly with only 3x32x32 vs 3x256x256 parameters.

The implementations I've looked at does similarly as the code you referenced and I also believe this is more correct, although the way we've done it also seems to work. Maybe you can do a PR on this?

Great idea regarding einsum, will start working on it :)

**Comment by johngrabner** [comment]
Thanks for the response.  I will do some experiments and let you know if it helps.

**Comment by AladdinPerzon** [comment]
Let me know what you find! Video on einsum is done now too :+1:

**Comment by johngrabner** [comment]
I watched it as soon as the notification popped up. Excellent video. You have a talent for presenting information efficiently.





Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone



-------- Original message --------
